redis:
  url: localhost
  port: 6379
  to_visit: to_visit
  visited: visited
save:
  where: to_redis
  member: data
scraper:
  start_url: <starting_url>
  request_timeout: 60
load_balancer:
  requests:
    per_minute: 60
    per_second: 1